The Chat Of Chutulhu (users)/Chat.WebAdmin/Controllers/CategoriasController.cs
using Chat.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.WebAdmin.Controllers
{
    public class CategoriasController : Controller
    {
        CategoriaBL _categoriasBL;
        public CategoriasController()
        {
            _categoriasBL = new CategoriaBL();

        }
        // GET: Categorias
        public ActionResult Index()
        {
            var lista_Cate = _categoriasBL.MostrarCategorias();
            return View(lista_Cate);
        }
        public ActionResult Crear()
        {
            var Nueva_Categoria = new Categoria();
            return View(Nueva_Categoria);
        }
        [HttpPost]
        public ActionResult Crear(Categoria categoria)
        {
            if(ModelState.IsValid)
            {
                _categoriasBL.GuardarCategoria(categoria);
                return RedirectToAction("Index");
            }
            return View(categoria);
        }
        public ActionResult Editar(int id)
        {
           var categoria = _categoriasBL.MostrarCategorias(id);

            return View(categoria);
        }
        [HttpPost]
        public ActionResult Editar(Categoria categoria)
        {
            _categoriasBL.GuardarCategoria(categoria);
            return RedirectToAction("Index");
        }
        public ActionResult Detalle(int id)
        {
            var categoria = _categoriasBL.MostrarCategorias(id);

            return View(categoria);
        }
        public ActionResult Eliminar(int id)
        {
            var categoria = _categoriasBL.MostrarCategorias(id);

            return View(categoria);
        }
        [HttpPost]
        public ActionResult Eliminar(Categoria categoria)
        {
            _categoriasBL.EliminarCategoria(categoria.ID);
            return RedirectToAction("Index");
        }

    }
}

The Chat Of Chutulhu (users)/Chat.WebAdmin/Controllers/DescargaController.cs
using Chat.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.WebAdmin.Controllers
{
    public class DescargaController : Controller
    {
        DescargaBL _descargaBL;
        public DescargaController()
        {
            _descargaBL = new DescargaBL();
        }
        // GET: Descarga
        public ActionResult Index()
        {
            var listaLinks = _descargaBL.MostrarLinks();
            return View(listaLinks);
        }
        public ActionResult Crear()
        {
            var Nuevolink = new Descarga();


            return View(Nuevolink);
        }

    }
}

The Chat Of Chutulhu (users)/Chat.WebAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.WebAdmin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

The Chat Of Chutulhu (users)/Chat.WebAdmin/Controllers/LibroController.cs
using Chat.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.WebAdmin.Controllers
{
    public class LibroController : Controller
    {
        LibroBL _libroBL;
        CategoriaBL _categoriasBL;
        DescargaBL _descargaBL;
        public LibroController()
        {
            _libroBL= new LibroBL();
            _categoriasBL = new CategoriaBL();
            _descargaBL = new DescargaBL(); 

        }
        // GET: Libro
        public ActionResult Index()
        {
            var lista_libros = _libroBL.MostrarLibros();
            return View(lista_libros);
        }
        public ActionResult Crear()
        {
            var Nuevo_libro = new Libro();
            var categoria = _categoriasBL.MostrarCategorias();
            ViewBag.ListaCategoria = new SelectList(categoria, "ID", "Nombre");
          
            return View(Nuevo_libro);
        }


        [HttpPost]
        public ActionResult Crear(Libro libro, HttpPostedFileBase imagen)
        {

            if (ModelState.IsValid)
            {
               if (imagen != null)
                {
                    libro.Urlimag = GuardarImagen(imagen);
                }
                _libroBL.GuardarLibro(libro);
                return RedirectToAction("Index");
            }
            var categoria = _categoriasBL.MostrarCategorias();
            ViewBag.ListaCategoria = new SelectList(categoria, "ID", "Nombre");
           ;
            return View(libro);
        }
        public ActionResult Editar(int id)
        {
            var libro = _libroBL.Mostrarlibros(id);

            return View(libro);
        }
        [HttpPost]
        public ActionResult Editar(Libro libro, HttpPostedFileBase imagen)
        {
            if (ModelState.IsValid)
            {
                if (imagen != null)
                {
                    libro.Urlimag = GuardarImagen(imagen);
                }

                _libroBL.GuardarLibro(libro);

                return RedirectToAction("Index");
            }
                return View(libro);
        }
           
        
        public ActionResult Detalle(int id)
        {
            var libro = _libroBL.Mostrarlibros(id);

            return View(libro);
        }
        public ActionResult Eliminar(int id)
        {
            var libro = _libroBL.Mostrarlibros(id);

            return View(libro);
        }
        [HttpPost]
        public ActionResult Eliminar(Libro libro)
        {
            _libroBL.EliminarLibro(libro.Id);
            return RedirectToAction("Index");
        }

        private string GuardarImagen(HttpPostedFileBase imagen)
        {
            string path = Server.MapPath("~/Imagenes/" + imagen.FileName);
            imagen.SaveAs(path);
            return "/Imagenes/" + imagen.FileName;
        }


    }
}

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Categorias/Crear.cshtml
@model Chat.BL.Categoria

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Categorias/Detalle.cshtml
@model Chat.BL.Categoria

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Categorias/Editar.cshtml
@model Chat.BL.Categoria

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Categorias/Eliminar.cshtml
@model Chat.BL.Categoria

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Categorias/Index.cshtml
@model IEnumerable<Chat.BL.Categoria>

@{
    ViewBag.Title = "Categorias";
}

<h2>Categorias</h2>

<p>
    @Html.ActionLink("Nueva Categoria", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.ID }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.ID }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.ID })
        </td>
    </tr>
}

</table>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Descarga/Index.cshtml
@model IEnumerable<Chat.BL.Descarga>

@{
    ViewBag.Title = "Descargas";
}

<h2>Links</h2>

<p>
    @Html.ActionLink("Nuevo Link", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Libro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.libroId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Administradores </h2>
<body>
    <center>
      <img src="~/Imagenes/portada.jpg" alt="Chat Of Cthulhu" @*/*align="middle"*/*@ style="width: 100%; max-width: 600px;"  />
</center> 
 </body>
   
  <body 
      style="background-color:#000000;">
</body>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Libro/Crear.cshtml
@model Chat.BL.Libro

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

@using (Html.BeginForm("Crear","Libro",FormMethod.Post, new { enctype= "Multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
         <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
      <div class="form-group">
            @Html.LabelFor(model => model.ListaCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ListaCategoria", null, htmlAttributes: new { @class = "form -control" })
                @Html.ValidationMessageFor(model => model.ListaCategoria, "", new { @class = "text-danger" })
            </div>
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.Sipnosis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sipnosis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sipnosis, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        
        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar Imagen</label>
            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Libro/Detalle.cshtml
@model Chat.BL.Libro

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sipnosis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sipnosis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Urlimag)
        </dt>

        <dd>
            <img src="@Model.Urlimag" alt="@Model.Nombre" style="width:200px; height:auto;" />
        </dd>
         <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Libro/Editar.cshtml
@model Chat.BL.Libro

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Libro", FormMethod.Post, new { enctype = "Multipar/form-data" }))
{
                @Html.AntiForgeryToken()

        <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sipnosis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sipnosis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sipnosis, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                <label class="control-label col-md-2">Seleccionar Imagen</label>
                <div class="col-md-2">
                    <input type="file" name="imagen" id="imagen" />
                </div>
                <div class="col-md-8">
                    <img src="@Model.Urlimag" alt="@Model.Nombre" style="width:200px; height:auto;" />
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}            

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Libro/Eliminar.cshtml
@model Chat.BL.Libro

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sipnosis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sipnosis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Urlimag)
        </dt>

        <dd>
            <img src="@Model.Urlimag" alt="@Model.Nombre" style="width:200px; height:auto;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Libro/Index.cshtml
@model IEnumerable<Chat.BL.Libro>

@{
    ViewBag.Title = "Libros";
}

<h2>Libros</h2>

<p>
    @Html.ActionLink("Nuevos Libros", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sipnosis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Urlimag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sipnosis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
              <img src="@item.Urlimag" alt="@item.Sipnosis" style="width: 64px; height:auto;" /> 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalle", "Detalle", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
            </td>
        </tr>
    }

</table>

The Chat Of Chutulhu (users)/Chat.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - The Chat Of Cthulhu</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Chat Of Cthulhu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio","Index","Home")
                    </li>
                    <li>
                        @Html.ActionLink("Categorias", "Index", "Categorias")
                    </li>
                    <li>
                        @Html.ActionLink("Libros", "Index", "Libro")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The Chat Of Cthulhu</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>